steps:
- name: npm-install
  entrypoint: npm
  args: ["install"]
- name: npm-create-env-vars
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - "BOT_TOKEN=${_BOT_TOKEN}"
    - "RIOT_API_KEY=${_RIOT_API_KEY}"
    - "RIOT_API_BASE_URL=${_RIOT_API_BASE_URL}"
- name: npm-run-build
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"